### PR TITLE
[v1.28] Bump dependencies to k8s 1.28 | Update wrangler to v2.1.3

### PR DESCRIPTION
**Pull request by chiukapoor**
### Update
* Bump k8s dependencies to 0.28.6
* Bump wrangler to v2.1.3

### Related
* https://github.com/rancher/rancher/issues/43109

### CODE REVIEW

**Review by kinarashah — APPROVED** [review]
@MbolotSuse Is this ok to merge?

**Comment by MbolotSuse** [comment]
@kinarashah There's another PR (#47) which was recently merged that aims to update wrangler. This will need a rebase before it can be merged at minimum. Let me know when that's done and I can give this another look.

**Comment by chiukapoor** [comment]
@MbolotSuse rebased the PR, please review.

**Review by MbolotSuse — APPROVED** [review]

**Review by tomleb — APPROVED** [review]
I don't see a release for wrangler v2.1.3 but just a tag, any reason?

Otherwise, looks good.

**Comment by kinarashah** [comment]
@tomleb Thanks for noticing, created a release from the tag https://github.com/rancher/wrangler/releases/tag/v2.1.3

**Pull request merged**
